project:
  type: website
execute:
  freeze: auto
website:
  title: "Spinning coral"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pschmidtke
      - icon: mastodon
        href: https://masto.ai/@pschmidtke
format:
  html:
    include-in-header:
      - text: |
          <script async data-id="101409313" src="//static.getclicky.com/js"></script>
    theme:
      dark: darkly
      light: flatly
    css: styles.scss
comments:
  utterances:
    repo: pschmidtke/blog
  hypothesis: true



