project:
  type: website
execute:
  freeze: auto
website:
  title: "Spinning coral"
  google-analytics: "G-9LJZZ6RBGN"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pschmidtke
      - icon: mastodon
        href: https://masto.ai/@pschmidtke
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.scss



