project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  title: "Spinning coral"
  google-analytics: "372266383"
  cookie-consent:
    type: express
    style: headline
    palette: dark
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pschmidtke
      - icon: mastodon
        href: https://masto.ai/@pschmidtke
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.scss



