name: py38_rdkit_blog
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - rdkit
  - jupyter
  - nglview
  - networkx
  - ipywidgets
  - ipycytoscape
  - ipython-sql
  - jupyterlab
  - matplotlib
  - openbabel
  - altair
  - requests