name: py310_rdkit_blog
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - seaborn
  - pandas
  - rdkit
  - jupyter
  - nglview
  - networkx
  - ipywidgets
  - ipykernel
  - ipycytoscape
  - ipython-sql
  - jupyterlab
  - matplotlib
  - openbabel
  - requests