About this blog

During my everyday work I'm in contact with a lot of people supporting early stage drug discovery. During this work I use proprietary tools, but also several open source tools. Usually you face several issues a lot of other people faced before or will face in the future. One aim of this blog is to share these quirks and allow others to gain some time, trigger discussions, get feedback and improve the field as openly as possible.

I'll likely write about whatever crosses my mind here, but it'll surely focus on topics around cheminformatics, bioinformatics, binding sites, maybe a few papers. Let's see where this goes.

## About myself

I'm a European citizen, dad of two beautiful girls and I am currently stranded in France. I did my PhD in Xavier Barril's excellent group at the University of Barcelona, then a post-doc in molecular modelling within a French pharma company. However, I spent most of my "professional career" at [Discngine](https://www.discngine.com) based in Paris, France. A great place to work, even though we tend not to apply for these fancy marketing labels ;)

Together with Vincent Le Guilloux (also at Discngine now) we developed [fpocket](https://github.com/Discngine/fpocket) while we were still finishing our Bioinformatics Masters degree. After that I wrote a bunch of papers (during my PhD) mainly on binding site characterisation, druggability assessment, structure kinetic relationships and a couple of other things more. 

Together with a great team at Discngine, I also started [3decision](https://3decision.discngine.cloud) a subscription-based structure repo & analytics platform a few years back now. 

## Spinning coral 

The name of the blog was inspired by my 7 years old daughter, Anna. She always wants to play with 3D molecular viewers on my screen. She started to do that when she was around 5, having no idea what a protein is and looks like she basically asks me: "Daddy, may I spin the coral again?".  

## Inspirations

Having a blog on cheminformatics etc is not the brightest and newest idea. I've had a lot of good reads thanks to all of these excellent & very well known blogs: 

- [https://iwatobipen.wordpress.com/](https://iwatobipen.wordpress.com)
- [http://practicalcheminformatics.blogspot.com/](http://practicalcheminformatics.blogspot.com)
- [https://greglandrum.github.io/rdkit-blog/](https://greglandrum.github.io/rdkit-blog/)
